In [36]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [37]:
torrero_bird = pd.read_csv("dataset\\penguins.csv")

In [38]:
torrero_bird

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [39]:
torrero_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [40]:
torrero_bird.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [41]:
torrero_bird.describe().T

,count,mean,std,min,25%,50%,75%,max
bill_length_mm,342.0,43.921930,5.459584,32.1,39.225,44.45,48.5,59.6
bill_depth_mm,342.0,17.151170,1.974793,13.1,15.600,17.30,18.7,21.5
flipper_length_mm,342.0,200.915205,14.061714,172.0,190.000,197.00,213.0,231.0
body_mass_g,342.0,4201.754386,801.954536,2700.0,3550.000,4050.00,4750.0,6300.0

In [42]:
torrero_bird['body_mass_g']

0      3750.0
1      3800.0
2      3250.0
3         NaN
4      3450.0
        ...
339       NaN
340    4850.0
341    5750.0
342    5200.0
343    5400.0
Name: body_mass_g, Length: 344, dtype: float64

In [43]:
torrero_bird['species']

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: object

<h1> How to create your own column</h1>

In [44]:
torrero_bird['weight_kg'] = torrero_bird['body_mass_g'] / 1000

In [45]:
torrero_bird

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,weight_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,3.75
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,3.80
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,3.25
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,3.45
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE,4.85
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE,5.75
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE,5.20
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE,5.40

In [46]:
torrero_bird['weight_kg'] = np.round(torrero_bird['body_mass_g'] / 1000, 1)

In [47]:
torrero_bird

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,weight_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,3.8
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,3.8
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,3.2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,3.4
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE,4.8
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE,5.8
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE,5.2
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE,5.4

<h1>Applying functions  to a column</h1>

In [48]:
torrero_bird['body_mass_g'].mean()

4201.754385964912

In [49]:
torrero_bird['body_mass_g'].median()

4050.0

In [50]:
torrero_bird['body_mass_g'].mode()

0    3800.0
Name: body_mass_g, dtype: float64

<h1> Checking of null values </h1>

In [51]:
torrero_bird.isnull

<bound method DataFrame.isnull of     species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0
1    Adelie  Torgersen            39.5           17.4              186.0
2    Adelie  Torgersen            40.3           18.0              195.0
3    Adelie  Torgersen             NaN            NaN                NaN
4    Adelie  Torgersen            36.7           19.3              193.0
..      ...        ...             ...            ...                ...
339  Gentoo     Biscoe             NaN            NaN                NaN
340  Gentoo     Biscoe            46.8           14.3              215.0
341  Gentoo     Biscoe            50.4           15.7              222.0
342  Gentoo     Biscoe            45.2           14.8              212.0
343  Gentoo     Biscoe            49.9           16.1              213.0

     body_mass_g     sex  weight_kg
0         3750.0    MALE        3.8
1         3800.0  FEMALE        3.8
2         3250.0  FEMALE        3.2
3            NaN     NaN        NaN
4         3450.0  FEMALE        3.4
..           ...     ...        ...
339          NaN     NaN        NaN
340       4850.0  FEMALE        4.8
341       5750.0    MALE        5.8
342       5200.0  FEMALE        5.2
343       5400.0    MALE        5.4

[344 rows x 8 columns]>

In [52]:
torrero_bird.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
weight_kg             2
dtype: int64

<h1> What to do with null values</h1>

In [53]:
#delete the row

#place / fillup the missing data

<h1> Filling the missing values in the data frame </h1>

In [54]:
torrero_bird['bill_length_mm']

0      39.1
1      39.5
2      40.3
3       NaN
4      36.7
       ...
339     NaN
340    46.8
341    50.4
342    45.2
343    49.9
Name: bill_length_mm, Length: 344, dtype: float64

In [55]:
#torrero_bird['bill_length_mm'] = torrero_bird['bill_length_mm'].mean()
torrero_bird['bill_length_mm'] = torrero_bird['bill_length_mm'].fillna(torrero_bird['bill_length_mm'].mean())

In [56]:
torrero_bird.isnull().sum()

species               0
island                0
bill_length_mm        0
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
weight_kg             2
dtype: int64

In [57]:
torrero_bird['sex'] = torrero_bird['sex'].fillna(torrero_bird['sex'].mode()[0])

In [58]:
torrero_bird.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        2
flipper_length_mm    2
body_mass_g          2
sex                  0
weight_kg            2
dtype: int64

In [59]:
torrero_bird['sex'].mode()

0    MALE
Name: sex, dtype: object

In [60]:
torrero_bird['bill_depth_mm'] = torrero_bird['bill_depth_mm'].fillna(torrero_bird['bill_depth_mm'].mean())

In [61]:
torrero_bird.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    2
body_mass_g          2
sex                  0
weight_kg            2
dtype: int64

In [62]:
torrero_bird['flipper_length_mm'] = torrero_bird['flipper_length_mm'].fillna(torrero_bird['flipper_length_mm'].mean())

In [63]:
torrero_bird.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          2
sex                  0
weight_kg            2
dtype: int64

In [64]:
torrero_bird['body_mass_g'] = torrero_bird['body_mass_g'].fillna(torrero_bird['body_mass_g'].mean())

In [65]:
torrero_bird.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
weight_kg            2
dtype: int64

In [66]:
torrero_bird['weight_kg'] = torrero_bird['weight_kg'].fillna(torrero_bird['weight_kg'].mean())

In [67]:
torrero_bird.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
weight_kg            0
dtype: int64

<h1>COLUMN DAT TYPE</h1>

In [68]:
torrero_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    object
 7   weight_kg          344 non-null    float64
dtypes: float64(5), object(3)
memory usage: 21.6+ KB

In [69]:
torrero_bird['species'] = torrero_bird['species'].astype('category')

In [70]:
torrero_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    category
 1   island             344 non-null    object
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    object
 7   weight_kg          344 non-null    float64
dtypes: category(1), float64(5), object(2)
memory usage: 19.4+ KB

In [71]:
torrero_bird['island'] = torrero_bird['island'].astype('category')

In [72]:
torrero_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    category
 1   island             344 non-null    category
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    object
 7   weight_kg          344 non-null    float64
dtypes: category(2), float64(5), object(1)
memory usage: 17.2+ KB

In [73]:
torrero_bird['sex'] = torrero_bird['sex'].astype('category')

In [74]:
torrero_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    category
 1   island             344 non-null    category
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    category
 7   weight_kg          344 non-null    float64
dtypes: category(3), float64(5)
memory usage: 15.0 KB