In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
torrero_bird = pd.read_csv("dataset\\penguins.csv")

In [3]:
torrero_bird

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

<h1>BASIC CHECKING AND DESCRIPTIVE ANALYTICS</h1>
<h3>.info(), .describe()</h3>

In [4]:
torrero_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [5]:
torrero_bird.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

<h1>TO FLIP THE DESCRIBE TABLE // TRANSPOSE</h1>

In [6]:
torrero_bird.describe().T

,count,mean,std,min,25%,50%,75%,max
bill_length_mm,342.0,43.921930,5.459584,32.1,39.225,44.45,48.5,59.6
bill_depth_mm,342.0,17.151170,1.974793,13.1,15.600,17.30,18.7,21.5
flipper_length_mm,342.0,200.915205,14.061714,172.0,190.000,197.00,213.0,231.0
body_mass_g,342.0,4201.754386,801.954536,2700.0,3550.000,4050.00,4750.0,6300.0

In [7]:
torrero_bird['body_mass_g']

0      3750.0
1      3800.0
2      3250.0
3         NaN
4      3450.0
        ...
339       NaN
340    4850.0
341    5750.0
342    5200.0
343    5400.0
Name: body_mass_g, Length: 344, dtype: float64

In [8]:
torrero_bird['bill_depth_mm']

0      18.7
1      17.4
2      18.0
3       NaN
4      19.3
       ...
339     NaN
340    14.3
341    15.7
342    14.8
343    16.1
Name: bill_depth_mm, Length: 344, dtype: float64

<h1>How to create your own column </h1>

<h6>round(number to round, number of decimal place)</h6>
<h6>issue round function only works for a singular linear operation</h6>

In [9]:
#torrero_bird['weight_kg'] = torrero_bird['body_mass'] / 1000
torrero_bird['weight_kg'] = np.round(torrero_bird['body_mass_g'] / 1000, 1)

In [10]:
torrero_bird

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,weight_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,3.8
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,3.8
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,3.2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,3.4
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE,4.8
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE,5.8
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE,5.2
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE,5.4

<h1> Applying functions to a column</h1>
<h5>mean - average</h5>
<h5>median - middle data</h5>
<h5>mode - most frequent</h5>

In [11]:
torrero_bird['body_mass_g'].mean()

4201.754385964912

In [12]:
torrero_bird['body_mass_g'].median()

4050.0

In [13]:
torrero_bird['body_mass_g'].mode()

0    3800.0
Name: body_mass_g, dtype: float64

<h1>Checking of null values</h1>

In [14]:
torrero_bird.isnull()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,weight_kg
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
339,False,False,True,True,True,True,True,True
340,False,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False,False

In [15]:
torrero_bird.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
weight_kg             2
dtype: int64

<h1>What to do with null values</h1>
<h5>delete the row</h5>
<h5>place / fillup the missing data</h5>

<h1>FILLING UP MISSING VALUES IN THE DATA FRAME</h1>

In [16]:
torrero_bird['bill_length_mm']

0      39.1
1      39.5
2      40.3
3       NaN
4      36.7
       ...
339     NaN
340    46.8
341    50.4
342    45.2
343    49.9
Name: bill_length_mm, Length: 344, dtype: float64

In [17]:
#torrero_bird['bill_length_mm'] = torrero_bird['bill_length_mm'].mean()
torrero_bird['bill_length_mm'] = torrero_bird['bill_length_mm'].fillna(torrero_bird['bill_length_mm'].mean())

In [18]:
torrero_bird.isnull().sum()

species               0
island                0
bill_length_mm        0
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
weight_kg             2
dtype: int64

In [19]:
torrero_bird['bill_depth_mm'] = torrero_bird['bill_depth_mm'].fillna(torrero_bird['bill_depth_mm'].mean())

In [20]:
torrero_bird.isnull().sum()

species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     2
body_mass_g           2
sex                  11
weight_kg             2
dtype: int64

In [21]:
torrero_bird['flipper_length_mm'] = torrero_bird['flipper_length_mm'].fillna(torrero_bird['flipper_length_mm'].mean())

In [22]:
torrero_bird.isnull().sum()

species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     0
body_mass_g           2
sex                  11
weight_kg             2
dtype: int64

In [23]:
torrero_bird['body_mass_g'] = torrero_bird['body_mass_g'].fillna(torrero_bird['body_mass_g'].mean())

In [24]:
torrero_bird.isnull().sum()

species               0
island                0
bill_length_mm        0
bill_depth_mm         0
flipper_length_mm     0
body_mass_g           0
sex                  11
weight_kg             2
dtype: int64

In [25]:
torrero_bird['sex'] = torrero_bird['sex'].fillna(torrero_bird['sex'].mode()[0])

In [26]:
torrero_bird.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
weight_kg            2
dtype: int64

In [27]:
torrero_bird['sex'].mode()

0    MALE
Name: sex, dtype: object

In [28]:
torrero_bird['weight_kg'] = torrero_bird['weight_kg'].fillna(torrero_bird['weight_kg'].mean())

In [29]:
torrero_bird.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
weight_kg            0
dtype: int64

<h1>Using of .tail(), .head()</h1>

In [30]:
torrero_bird['species'].tail(20)

324    Gentoo
325    Gentoo
326    Gentoo
327    Gentoo
328    Gentoo
329    Gentoo
330    Gentoo
331    Gentoo
332    Gentoo
333    Gentoo
334    Gentoo
335    Gentoo
336    Gentoo
337    Gentoo
338    Gentoo
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, dtype: object

In [31]:
torrero_bird['species'].head(20)

0     Adelie
1     Adelie
2     Adelie
3     Adelie
4     Adelie
5     Adelie
6     Adelie
7     Adelie
8     Adelie
9     Adelie
10    Adelie
11    Adelie
12    Adelie
13    Adelie
14    Adelie
15    Adelie
16    Adelie
17    Adelie
18    Adelie
19    Adelie
Name: species, dtype: object

<h1>How to drop column?</h1>

<h6>torrero_bird.drop(column = 'weight_kg')</h6>

<h1>COLUMN DATA TYPE</h1>

In [32]:
torrero_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    object
 7   weight_kg          344 non-null    float64
dtypes: float64(5), object(3)
memory usage: 21.6+ KB

In [33]:
torrero_bird['species'] = torrero_bird['species'].astype('category')

In [34]:
torrero_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    category
 1   island             344 non-null    object
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    object
 7   weight_kg          344 non-null    float64
dtypes: category(1), float64(5), object(2)
memory usage: 19.4+ KB

In [35]:
torrero_bird['island'] = torrero_bird['island'].astype('category')

In [36]:
torrero_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    category
 1   island             344 non-null    category
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    object
 7   weight_kg          344 non-null    float64
dtypes: category(2), float64(5), object(1)
memory usage: 17.2+ KB

In [37]:
torrero_bird['sex'] = torrero_bird['sex'].astype('category')

In [38]:
torrero_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    category
 1   island             344 non-null    category
 2   bill_length_mm     344 non-null    float64
 3   bill_depth_mm      344 non-null    float64
 4   flipper_length_mm  344 non-null    float64
 5   body_mass_g        344 non-null    float64
 6   sex                344 non-null    category
 7   weight_kg          344 non-null    float64
dtypes: category(3), float64(5)
memory usage: 15.0 KB

<h1>DATA EXPLORATION</h1>

In [39]:
torrero_bird['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [40]:
torrero_bird['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

<h1>DOES THE ADELIE PENGUIN LIVE EXCLUSIVELY ON AN ISLAND</h1>

In [41]:
torrero_bird['species'] == 'Adelie'

0       True
1       True
2       True
3       True
4       True
       ...
339    False
340    False
341    False
342    False
343    False
Name: species, Length: 344, dtype: bool

In [42]:
torrero_bird[torrero_bird['species'] == 'Adelie']

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,weight_kg
0,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,MALE,3.800000
1,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,FEMALE,3.800000
2,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,FEMALE,3.200000
3,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,MALE,4.202047
4,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,FEMALE,3.400000
...,...,...,...,...,...,...,...,...
147,Adelie,Dream,36.60000,18.40000,184.000000,3475.000000,FEMALE,3.500000
148,Adelie,Dream,36.00000,17.80000,195.000000,3450.000000,FEMALE,3.400000
149,Adelie,Dream,37.80000,18.10000,193.000000,3750.000000,MALE,3.800000
150,Adelie,Dream,36.00000,17.10000,187.000000,3700.000000,FEMALE,3.700000
151,Adelie,Dream,41.50000,18.50000,201.000000,4000.000000,MALE,4.000000

In [43]:
torrero_bird['island'] == 'Biscoe'

0      False
1      False
2      False
3      False
4      False
       ...
339     True
340     True
341     True
342     True
343     True
Name: island, Length: 344, dtype: bool

In [44]:
torrero_bird[torrero_bird['island'] == 'Biscoe']

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,weight_kg
20,Adelie,Biscoe,37.80000,18.30000,174.000000,3400.000000,FEMALE,3.400000
21,Adelie,Biscoe,37.70000,18.70000,180.000000,3600.000000,MALE,3.600000
22,Adelie,Biscoe,35.90000,19.20000,189.000000,3800.000000,FEMALE,3.800000
23,Adelie,Biscoe,38.20000,18.10000,185.000000,3950.000000,MALE,4.000000
24,Adelie,Biscoe,38.80000,17.20000,180.000000,3800.000000,MALE,3.800000
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,43.92193,17.15117,200.915205,4201.754386,MALE,4.202047
340,Gentoo,Biscoe,46.80000,14.30000,215.000000,4850.000000,FEMALE,4.800000
341,Gentoo,Biscoe,50.40000,15.70000,222.000000,5750.000000,MALE,5.800000
342,Gentoo,Biscoe,45.20000,14.80000,212.000000,5200.000000,FEMALE,5.200000
343,Gentoo,Biscoe,49.90000,16.10000,213.000000,5400.000000,MALE,5.400000

<h1>ADELIE ON BISCOE ISLAND</h1>

In [45]:
adelie_peng = torrero_bird[(torrero_bird['species'] == 'Adelie') & (torrero_bird['island'] == 'Biscoe')].info()

<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, 20 to 115
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            44 non-null     category
 1   island             44 non-null     category
 2   bill_length_mm     44 non-null     float64
 3   bill_depth_mm      44 non-null     float64
 4   flipper_length_mm  44 non-null     float64
 5   body_mass_g        44 non-null     float64
 6   sex                44 non-null     category
 7   weight_kg          44 non-null     float64
dtypes: category(3), float64(5)
memory usage: 2.6 KB

In [46]:
adelie_peng = torrero_bird[(torrero_bird['species'] == 'Adelie') & (torrero_bird['island'] == 'Biscoe')]

In [47]:
np.round(adelie_peng['weight_kg'].mean(),1)

3.7

In [48]:
adelie_peng = torrero_bird[(torrero_bird['species'] == 'Adelie') & (torrero_bird['island'] == 'Dream')].info()

<class 'pandas.core.frame.DataFrame'>
Index: 56 entries, 30 to 151
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            56 non-null     category
 1   island             56 non-null     category
 2   bill_length_mm     56 non-null     float64
 3   bill_depth_mm      56 non-null     float64
 4   flipper_length_mm  56 non-null     float64
 5   body_mass_g        56 non-null     float64
 6   sex                56 non-null     category
 7   weight_kg          56 non-null     float64
dtypes: category(3), float64(5)
memory usage: 3.2 KB

In [49]:
adelie_peng = torrero_bird[(torrero_bird['species'] == 'Adelie') & (torrero_bird['island'] == 'Torgesen')].info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            0 non-null      category
 1   island             0 non-null      category
 2   bill_length_mm     0 non-null      float64
 3   bill_depth_mm      0 non-null      float64
 4   flipper_length_mm  0 non-null      float64
 5   body_mass_g        0 non-null      float64
 6   sex                0 non-null      category
 7   weight_kg          0 non-null      float64
dtypes: category(3), float64(5)
memory usage: 388.0 bytes

In [50]:
torrero_bird['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [51]:
56+52+44

152

<h1>Gentoo Species</h1>

In [52]:
#torrero_bird['species'] == 'Gentoo'
#torrero_bird['species'] == 'Dream'
torrero_bird[torrero_bird['species'] == 'Gentoo'].count()

species              124
island               124
bill_length_mm       124
bill_depth_mm        124
flipper_length_mm    124
body_mass_g          124
sex                  124
weight_kg            124
dtype: int64

In [53]:
torrero_bird['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

In [54]:
#torrero_bird[torrero_bird['island'] == 'Biscoe'].count()
#torrero_bird[(torrero_bird['species'] == 'Gentoo') & (torrero_bird['island'] == 'Biscoe')].count()
#torrero_bird[(torrero_bird['species'] == 'Gentoo') & (torrero_bird['island'] == 'Torgesen')].count()

gentoo_peng = torrero_bird[(torrero_bird['species'] == 'Gentoo') & (torrero_bird['island'] == 'Biscoe')]

In [55]:
#gentoo_peng['weight_kg'].mean()
np.round(gentoo_peng['weight_kg'].mean(),1)

5.1

<h1>INSIGHT 1</h1>
<h3>Gentoo Penguins lives exclusively on the Biscoe Island</h3>

In [56]:
gentoo_peng = torrero_bird[(torrero_bird['species'] == 'Gentoo') & (torrero_bird['island'] == 'Biscoe')]
gentoo_peng

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,weight_kg
220,Gentoo,Biscoe,46.10000,13.20000,211.000000,4500.000000,FEMALE,4.500000
221,Gentoo,Biscoe,50.00000,16.30000,230.000000,5700.000000,MALE,5.700000
222,Gentoo,Biscoe,48.70000,14.10000,210.000000,4450.000000,FEMALE,4.400000
223,Gentoo,Biscoe,50.00000,15.20000,218.000000,5700.000000,MALE,5.700000
224,Gentoo,Biscoe,47.60000,14.50000,215.000000,5400.000000,MALE,5.400000
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,43.92193,17.15117,200.915205,4201.754386,MALE,4.202047
340,Gentoo,Biscoe,46.80000,14.30000,215.000000,4850.000000,FEMALE,4.800000
341,Gentoo,Biscoe,50.40000,15.70000,222.000000,5750.000000,MALE,5.800000
342,Gentoo,Biscoe,45.20000,14.80000,212.000000,5200.000000,FEMALE,5.200000
343,Gentoo,Biscoe,49.90000,16.10000,213.000000,5400.000000,MALE,5.400000

<h1>INSIGHT 2</h1>
<h3>Chinstrap Penguins lives exclusively on the Dream Island</h3>

In [57]:
chins_peng = torrero_bird[(torrero_bird['species'] == 'Chinstrap') & (torrero_bird['island'] == 'Dream')]
chins_peng

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,weight_kg
152,Chinstrap,Dream,46.5,17.9,192.0,3500.0,FEMALE,3.5
153,Chinstrap,Dream,50.0,19.5,196.0,3900.0,MALE,3.9
154,Chinstrap,Dream,51.3,19.2,193.0,3650.0,MALE,3.6
155,Chinstrap,Dream,45.4,18.7,188.0,3525.0,FEMALE,3.5
156,Chinstrap,Dream,52.7,19.8,197.0,3725.0,MALE,3.7
...,...,...,...,...,...,...,...,...
215,Chinstrap,Dream,55.8,19.8,207.0,4000.0,MALE,4.0
216,Chinstrap,Dream,43.5,18.1,202.0,3400.0,FEMALE,3.4
217,Chinstrap,Dream,49.6,18.2,193.0,3775.0,MALE,3.8
218,Chinstrap,Dream,50.8,19.0,210.0,4100.0,MALE,4.1
219,Chinstrap,Dream,50.2,18.7,198.0,3775.0,FEMALE,3.8

<h1>INSIGHT 3</h1>
<h3>Adelie Penguins lives exclusively on the islands: Biscoe, Dream, Torgesen Island</h3>

In [58]:
adelie_peng = torrero_bird[(torrero_bird['species'] == 'Adelie') & (torrero_bird['island'].isin(['Biscoe', 'Dream', 'Torgersen']))]
adelie_peng

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,weight_kg
0,Adelie,Torgersen,39.10000,18.70000,181.000000,3750.000000,MALE,3.800000
1,Adelie,Torgersen,39.50000,17.40000,186.000000,3800.000000,FEMALE,3.800000
2,Adelie,Torgersen,40.30000,18.00000,195.000000,3250.000000,FEMALE,3.200000
3,Adelie,Torgersen,43.92193,17.15117,200.915205,4201.754386,MALE,4.202047
4,Adelie,Torgersen,36.70000,19.30000,193.000000,3450.000000,FEMALE,3.400000
...,...,...,...,...,...,...,...,...
147,Adelie,Dream,36.60000,18.40000,184.000000,3475.000000,FEMALE,3.500000
148,Adelie,Dream,36.00000,17.80000,195.000000,3450.000000,FEMALE,3.400000
149,Adelie,Dream,37.80000,18.10000,193.000000,3750.000000,MALE,3.800000
150,Adelie,Dream,36.00000,17.10000,187.000000,3700.000000,FEMALE,3.700000
151,Adelie,Dream,41.50000,18.50000,201.000000,4000.000000,MALE,4.000000

<h1>INSIGHT 4</h1>
<h3>Gentoo species has an average weight of 5.1 kilograms</h3>

In [59]:
np.round(gentoo_peng['weight_kg'].mean(),1)

5.1

<h1>INSIGHT 4.1</h1>
<h3>Adelie species in Biscoe Island has an average weight of 3.7 kilograms</h3>
<h3>Adelie species in Dream Island has an average weight of 3.7 kilograms</h3>
<h3>Adelie species in Torgesen Island has an average weight of 3.7 kilograms</h3>

In [60]:
#adelie_peng = torrero_bird[(torrero_bird['species'] == 'Adelie') & (torrero_bird['island'] == 'Biscoe')]
#adelie_peng = torrero_bird[(torrero_bird['species'] == 'Adelie') & (torrero_bird['island'] == 'Dream')]
#adelie_peng = torrero_bird[(torrero_bird['species'] == 'Adelie') & (torrero_bird['island'] == 'Torgesen')]
#adelie_peng['weight_kg'].mean(),1)
adel = torrero_bird.groupby(['species', 'island'], observed=True)['weight_kg'].mean()
np.round(adel,1)

species    island
Adelie     Biscoe       3.7
           Dream        3.7
           Torgersen    3.7
Chinstrap  Dream        3.7
Gentoo     Biscoe       5.1
Name: weight_kg, dtype: float64

<h1>INSIGHT 5</h1>
<h3>Chinstrap species has an average weight of 3.7 kilograms</h3>

In [61]:
np.round(chins_peng['weight_kg'].mean(),1)

3.7

<h1>INSIGHT 6</h1>
<h3>Adelie species has an average weight of 3.7 kilograms</h3>

In [62]:
np.round(adelie_peng['weight_kg'].mean(),1)

3.7

<h1>INSIGHT 7</h1>
<h3>Adelie species has an average weight of 3.7 kilograms</h3>
<h3>Chinstrap species has an average weight of 3.7 kilograms</h3>
<h3>Gentoo species has an average weight of 3.7 kilograms</h3>
<h4>Groupby</h4>

In [63]:
c = torrero_bird.groupby('species')['weight_kg'].mean()
np.round(c, 1)

C:\Users\User\AppData\Local\Temp\ipykernel_7288\2261452656.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  c = torrero_bird.groupby('species')['weight_kg'].mean()

species
Adelie       3.7
Chinstrap    3.7
Gentoo       5.1
Name: weight_kg, dtype: float64

<h1>INSIGHT 8</h1>
<h3>How many male/female penguin species live on the 3 different islands</h3>
<h6>count, size, mean, median, var, sum</h6>

In [64]:
g = torrero_bird.groupby(['species', 'island', 'sex']).count()
#g = torrero_bird.groupby(['species', 'island', 'sex', 'year')].size()
g

C:\Users\User\AppData\Local\Temp\ipykernel_7288\658195865.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = torrero_bird.groupby(['species', 'island', 'sex']).count()

                            bill_length_mm  bill_depth_mm  flipper_length_mm  \
species   island    sex
Adelie    Biscoe    FEMALE              22             22                 22
                    MALE                22             22                 22
          Dream     FEMALE              27             27                 27
                    MALE                29             29                 29
          Torgersen FEMALE              24             24                 24
                    MALE                28             28                 28
Chinstrap Biscoe    FEMALE               0              0                  0
                    MALE                 0              0                  0
          Dream     FEMALE              34             34                 34
                    MALE                34             34                 34
          Torgersen FEMALE               0              0                  0
                    MALE                 0              0                  0
Gentoo    Biscoe    FEMALE              58             58                 58
                    MALE                66             66                 66
          Dream     FEMALE               0              0                  0
                    MALE                 0              0                  0
          Torgersen FEMALE               0              0                  0
                    MALE                 0              0                  0

                            body_mass_g  weight_kg
species   island    sex
Adelie    Biscoe    FEMALE           22         22
                    MALE             22         22
          Dream     FEMALE           27         27
                    MALE             29         29
          Torgersen FEMALE           24         24
                    MALE             28         28
Chinstrap Biscoe    FEMALE            0          0
                    MALE              0          0
          Dream     FEMALE           34         34
                    MALE             34         34
          Torgersen FEMALE            0          0
                    MALE              0          0
Gentoo    Biscoe    FEMALE           58         58
                    MALE             66         66
          Dream     FEMALE            0          0
                    MALE              0          0
          Torgersen FEMALE            0          0
                    MALE              0          0

<h1>INSIGHT 9</h1>
<h3>Which is heavier amongst the penguin species, Male Or Female</h3>
<h5>Male is heavier than Female</h5>

In [65]:
c = torrero_bird.groupby(['species', 'sex'])['weight_kg'].mean()
np.round(c, 1)

C:\Users\User\AppData\Local\Temp\ipykernel_7288\3002177252.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  c = torrero_bird.groupby(['species', 'sex'])['weight_kg'].mean()

species    sex
Adelie     FEMALE    3.4
           MALE      4.0
Chinstrap  FEMALE    3.5
           MALE      3.9
Gentoo     FEMALE    4.7
           MALE      5.4
Name: weight_kg, dtype: float64

<h1>Unstack</h1>

In [66]:
c.unstack()

sex          FEMALE      MALE
species
Adelie     3.367123  4.017747
Chinstrap  3.523529  3.938235
Gentoo     4.681034  5.410637

<h1>Correlation</h1>
<h1>Question 10. Correlation between bill length and bill depth</h1>
<h3>Syntax Requirement</h3>
<ul>
    <li>Variable Name of Correlation Result</li>
    <li>First Column</li>
    <li>Corr Funtion</li>
    <li>Second Column</li>
</ul>

In [67]:
b_depth_length = torrero_bird['bill_length_mm'].corr(torrero_bird['bill_depth_mm'])

In [68]:
b_depth_length

-0.23505287035553277

<h1>Insight 10</h1>
<h3>There is no correlation between bill depth and bill length in the penguin species</h3>

In [69]:
bill_dl = torrero_bird['bill_length_mm'].corr(torrero_bird['bill_depth_mm'])
bill_dl>0.05

False

In [70]:
bill_dl

-0.23505287035553277

<h1>Insight 11</h1>
<h1>Is there a correlation between flipper length and body mass in the Penguin Species?</h1>

<h3>There is a correlation between flipper length and body mass in the Penguin Species</h3>

In [71]:
flipp_bmass = torrero_bird['flipper_length_mm'].corr(torrero_bird['body_mass_g'])
flipp_bmass>0.05

True

In [72]:
flipp_bmass

0.8712017673060112

<h1>Insight 12</h1>
<h1>Is there a correlation between bill depth and bill length in the Adelie Species?</h1>

<h3>There is a correlation between bill depth and bill length in the Adelie Species</h3>

In [73]:
peng_adelie = torrero_bird[(torrero_bird['species']=='Adelie')]
ade = peng_adelie['bill_depth_mm'].corr(peng_adelie['bill_length_mm'])
ade>0.05

True

In [74]:
ade

0.3731961190689369

<h1>Insight 13</h1>
<h1>Is there a correlation between bill depth and bill length in the Chinstrap Species?</h1>
<h3>There is a correlation between bill depth and bill length in the Chinstrap Species</h3>

In [75]:
peng_chins = torrero_bird[(torrero_bird['species']=='Chinstrap')]
chi = peng_chins['bill_depth_mm'].corr(peng_chins['bill_length_mm'])
chi>0.05

True

In [76]:
chi

0.6535362081800428

<h1>Insight 14</h1>
<h1>Is there a correlation between bill depth and bill length in the Gentoo Species?</h1>

<h3>There is a correlation between bill depth and bill length in the Gentoo Species</h3>

In [77]:
peng_gentoo = torrero_bird[(torrero_bird['species']=='Gentoo')]
gen = peng_gentoo['bill_depth_mm'].corr(peng_gentoo['bill_length_mm'])
gen>0.05

True

In [78]:
gen

0.6071518201350261

<h1>Insight 15</h1>
<h1>Is there a correlation between flipper length and body mass?</h1>

<h1>There is a correlation between flipper length and body mass.</h1>

In [79]:
flipper_mass_corr = torrero_bird['flipper_length_mm'].corr(torrero_bird['body_mass_g'])

if flipper_mass_corr > 0.05:
    print("There is a correlation between flipper length and body mass.")
else:
    print("There is no significant correlation between flipper length and body mass.")

There is a correlation between flipper length and body mass.

In [80]:
flipper_mass_corr

0.8712017673060112

<h1>Correlation Analysis between Qualitative Data and Quantitative</h1>
<h1>Package name: Scince Python - Scipy</h1>

In [81]:
pip install scipy

Requirement already satisfied: scipy in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (1.13.0)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: numpy<2.3,>=1.22.4 in c:\users\user\appdata\local\programs\python\python311\lib\site-packages (from scipy) (1.26.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

<h1>Insight 16</h1>

<h1>Testing Correlation using One-way ANOVA, Analysis of Variance</h1>

In [82]:
from scipy.stats import f_oneway

<h3>Syntax Requirements</h3>
<ul>
    <li>Specify the values of categorical data</li>
    <li>Specify quantitative data</li>
</ul>

In [83]:
#male
#female

f_stats, p_value = f_oneway(torrero_bird[torrero_bird['sex'] == 'MALE']['body_mass_g'],
                            torrero_bird[torrero_bird['sex'] == 'FEMALE']['body_mass_g'])

print(p_value)

3.0226600487050253e-15

In [84]:
#torrero_bird['sex'] == 'male'
torrero_bird[torrero_bird['sex'] == 'MALE']['body_mass_g']

0      3750.000000
3      4201.754386
5      3650.000000
7      4675.000000
8      3475.000000
          ...
336    4875.000000
337    6000.000000
339    4201.754386
341    5750.000000
343    5400.000000
Name: body_mass_g, Length: 179, dtype: float64

In [85]:
#torrero_bird['sex'] == 'female'
torrero_bird[torrero_bird['sex'] == 'FEMALE']['body_mass_g']

1      3800.0
2      3250.0
4      3450.0
6      3625.0
12     3200.0
        ...
332    4650.0
334    4375.0
338    4925.0
340    4850.0
342    5200.0
Name: body_mass_g, Length: 165, dtype: float64